#!/usr/bin/env python3
"""
FreeCAD Macro Documentation Updater

Scans FreeCAD macro directory, extracts metadata (name, description, version, author, license)
from macro file headers, and generates a structured Markdown documentation file.

Usage:
    python maintain_macros.py [--macros-dir DIR] [--output FILE]

Default macro directory: ~/.FreeCAD/Macro (platform-dependent)
Default output file: macros_documentation.md
"""

import os
import re
import argparse
import sys
from pathlib import Path

def default_macro_dir():
    """Return default FreeCAD macro directory based on OS."""
    home = Path.home()
    if sys.platform.startswith('win'):
        return home / 'AppData' / 'Roaming' / 'FreeCAD' / 'Macro'
    elif sys.platform.startswith('darwin'):
        return home / 'Library' / 'Preferences' / 'FreeCAD' / 'Macro'
    else:
        return home / '.FreeCAD' / 'Macro'

def parse_macro_header(filepath):
    """Extract metadata from a FreeCAD macro file (.FCMacro or .py).
    Returns dict with keys: name, description, version, author, license, file_path.
    """
    metadata = {
        'name': '',
        'description': '',
        'version': '',
        'author': '',
        'license': '',
        'file_path': str(filepath)
    }
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except Exception:
        return metadata

    # Remove Windows line endings
    content = content.replace('\r\n', '\n')

    # Patterns
    patterns = {
        'name': r'(?:^|\n)\s*#\s*(?:Macro|macro)\s+([^\n]+)',
        'description': r'(?:^|\n)\s*#\s*Description\s*[:=]?\s*([^\n]+)',
        'version': r'(?:^|\n)\s*#\s*Version\s*[:=]?\s*([^\n]+)',
        'author': r'(?:^|\n)\s*#\s*Author\s*[:=]?\s*([^\n]+)',
        'license': r'(?:^|\n)\s*#\s*License\s*[:=]?\s*([^\n]+)'
    }

    for key, pattern in patterns.items():
        match = re.search(pattern, content, re.IGNORECASE)
        if match:
            metadata[key] = match.group(1).strip()

    # If name not found, use filename without extension
    if not metadata['name']:
        metadata['name'] = filepath.stem

    return metadata

def scan_macros(macros_dir):
    """Scan macros_dir for .FCMacro and .py files, return list of metadata dicts."""
    macros = []
    if not macros_dir.exists():
        print(f"Warning: Macro directory {macros_dir} does not exist.", file=sys.stderr)
        return macros
    for filepath in macros_dir.iterdir():
        if filepath.is_file() and filepath.suffix.lower() in ('.FCMacro', '.py'):
            metadata = parse_macro_header(filepath)
            if metadata:
                macros.append(metadata)
    return macros

def generate_markdown(macros):
    """Generate Markdown documentation from list of macro metadata."""
    lines = []
    lines.append("# FreeCAD Macros Documentation\n")
    lines.append("Auto-generated by maintain_macros.py\n")
    lines.append(f"Total macros found: {len(macros)}\n")
    lines.append("---\n")

    # Sort by name
    macros_sorted = sorted(macros, key=lambda m: m['name'].lower())

    for macro in macros_sorted:
        lines.append(f"## {macro['name']}\n")
        if macro['description']:
            lines.append(f"**Description:** {macro['description']}\n")
        if macro['version']:
            lines.append(f"**Version:** {macro['version']}\n")
        if macro['author']:
            lines.append(f"**Author:** {macro['author']}\n")
        if macro['license']:
            lines.append(f"**License:** {macro['license']}\n")
        lines.append(f"**File:** `{macro['file_path']}`\n")
        lines.append("\n")

    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description='Generate FreeCAD macros documentation.')
    parser.add_argument('--macros-dir', type=str, default=str(default_macro_dir()),
                        help='Path to FreeCAD macro directory')
    parser.add_argument('--output', type=str, default='macros_documentation.md',
                        help='Output Markdown file')
    args = parser.parse_args()

    macros_dir = Path(args.macros_dir)
    output_path = Path(args.output)

    print(f"Scanning macros in: {macros_dir}")
    macros = scan_macros(macros_dir)
    if not macros:
        print("No macros found. Exiting.")
        sys.exit(1)

    print(f"Found {len(macros)} macro(s).")
    md_content = generate_markdown(macros)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md_content)

    print(f"Documentation written to: {output_path}")

if __name__ == '__main__':
    main()