#!/usr/bin/env python3
"""
Script to maintain the FreeCAD Macros documentation.
Fetches the list of macros from the FreeCAD wiki and compares it with a local cache.
Outputs a report of new macros that need to be documented.
"""

import argparse
import json
import logging
import os
import re
import sys
from datetime import datetime
from typing import Dict, List, Tuple

import requests
from bs4 import BeautifulSoup

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Constants
WIKI_URL = "https://wiki.freecad.org/Macros"
CACHE_FILE = "macros_cache.json"
REPORT_FILE = "new_macros_report.md"

def fetch_macros_page() -> str:
    """Fetch the Macros wiki page content."""
    logger.info(f"Fetching macros from {WIKI_URL}")
    try:
        response = requests.get(WIKI_URL, timeout=30)
        response.raise_for_status()
        return response.text
    except requests.RequestException as e:
        logger.error(f"Failed to fetch macros page: {e}")
        sys.exit(1)

def parse_macro_links(html: str) -> List[Dict[str, str]]:
    """Parse the HTML to extract macro names and links."""
    soup = BeautifulSoup(html, 'html.parser')
    macros = []
    # Macros are typically in a table or list; we look for links containing 'Macro_'
    # The macro page has a table with class 'wikitable' or similar.
    # For robustness, we find all links that start with '/Macro_' or 'Macro_'.
    for link in soup.find_all('a', href=True):
        href = link['href']
        if href.startswith('/Macro_') or href.startswith('Macro_'):
            # Remove leading slash and decode
            name = href.split('/')[-1] if '/' in href else href
            # Remove '_' at end if any?
            name = name.replace('_', ' ').strip()
            macros.append({
                'name': name,
                'url': f"https://wiki.freecad.org/{href}" if not href.startswith('http') else href,
                'description': link.get('title', '').strip() or 'No description'
            })
    # Deduplicate by url
    seen = set()
    unique = []
    for m in macros:
        if m['url'] not in seen:
            seen.add(m['url'])
            unique.append(m)
    return unique

def load_cache() -> Dict[str, any]:
    """Load the local cache of known macros."""
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    else:
        logger.info("No cache file found. Creating new cache.")
        return {'last_updated': None, 'macros': []}

def save_cache(cache: Dict[str, any]):
    """Save the cache to disk."""
    with open(CACHE_FILE, 'w', encoding='utf-8') as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)
    logger.info(f"Cache saved to {CACHE_FILE}")

def identify_new_macros(current: List[Dict[str, str]], cached: List[Dict[str, str]]) -> List[Dict[str, str]]:
    """Identify macros not present in the cached list."""
    cached_urls = {m['url'] for m in cached}
    new_macros = [m for m in current if m['url'] not in cached_urls]
    return new_macros

def generate_report(new_macros: List[Dict[str, str]]) -> str:
    """Generate a markdown report of new macros."""
    now = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')
    lines = [
        f"# New Macros Report - {now}",
        "",
        f"Found {len(new_macros)} new macro(s) that need documentation.",
        "",
        "| Macro Name | Description | URL |",
        "|------------|-------------|-----|"
    ]
    for macro in new_macros:
        desc = macro['description'].replace('|', '\|')
        name = macro['name'].replace('|', '\|')
        url = macro['url']
        lines.append(f"| {name} | {desc} | {url} |")
    lines.append("")
    lines.append("---")
    lines.append("*Automatically generated by maintain_macros.py*")
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description='Maintain FreeCAD Macros documentation.')
    parser.add_argument('--force', action='store_true', help='Force update cache and generate report even if no changes.')
    parser.add_argument('--output', type=str, default=REPORT_FILE, help='Output report file path.')
    args = parser.parse_args()

    # Fetch current macros
    html = fetch_macros_page()
    current_macros = parse_macro_links(html)
    logger.info(f"Found {len(current_macros)} macros on wiki.")

    # Load cache
    cache = load_cache()
    cached_macros = cache.get('macros', [])

    # Identify new macros
    new_macros = identify_new_macros(current_macros, cached_macros)
    logger.info(f"New macros to document: {len(new_macros)}")

    if new_macros or args.force:
        # Generate report
        report = generate_report(new_macros)
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(report)
        logger.info(f"Report written to {args.output}")
        # Update cache with current macros (only if we fetched successfully)
        cache['last_updated'] = datetime.utcnow().isoformat()
        cache['macros'] = current_macros
        save_cache(cache)
    else:
        logger.info("No new macros found. Cache is up to date.")

if __name__ == '__main__':
    main()
