<languages/>

{{TutorialInfo/it
|Topic=Modellazione
|Level=Utente esperto
|Author=NormandC
|Time=
|FCVersion=0.19.23300 o superiore
|Files=
}}

<span id="Purpose_in_Brief"></span>
== Scopo in breve ==

Lo scopo di questo tutorial è di presentare due diversi flussi di lavoro per la creazione di un pezzo fuso con sformi e raccordi. A seconda dei programmi CAD che si è utilizzato, si potrebbe avere familiarità con uno o con l'altro. Come esempio pratico, modelleremo un semplice supporto per cuscinetto.

Questa è la seconda parte del tutorial. In questo esempio si usa il flusso di lavoro che può essere chiamato del "corpo multiplo" e si utilizza solamente la parte superiore del supporto.

Ovviamente, per seguire questo tutorial è necessario attivare l'ambiente PartDesign.

[[Image:HolderTop2-19.jpg|400px]]
{{Caption|Tutorial del supporto di un cuscinetto - Supporto del cuscinetto finito (parte superiore)}}

<span id="Design_data"></span>
== Dati di progetto ==

Il supporto deve essere in grado di contenere un cuscinetto di 90 mm di diametro con una larghezza fino a 33 mm (ad esempio, DIN 630 tipo 2308). Il cuscinetto richiede una spalla alta almeno 4,5 mm nel supporto (e sull'albero). La parte superiore del supporto è imbullonata al fondo con due bulloni di 12 mm. A fianco del cuscinetto ci deve essere una scanalatura su entrambi i lati capace di contenere un anello di tenuta standard sull'albero DIN 3760: 38x55x7 o 40x55x7 su un lato e 50x68x8 sull'altro lato.

Il supporto sarà prodotto con un getto in sabbia con uno spessore minimo della parete di 5 mm, un angolo di sforno con di 2 gradi e un raggio di raccordo minimo di 3 mm .

<br clear=all>

<span id="Setting_up_the_skeleton_geometry"></span>
== Impostazione della geometria di scheletro ==

[[Image:HolderTop2-2.png|Sketch della geometria scheletro|thumb|right|400px]]
Creare una nuova parte nell'ambiente PartDesign. Rinominare il corpo da come  viene creato per impostazione predefinita in "Skeleton". Questo corpo probabilmente è già attivato, cosa che si può vedere dallo sfondo blu nell'albero delle proprietà. Creare un nuovo schizzo sul piano YZ contenente il contorno dell'albero, i cuscinetti e gli anelli di tenuta. Dopo aver terminato lo schizzo, eseguire con esso una operazione di rivoluzione. Questa funzione "Scheletro" sarà utilizzata successivamente come riferimento per la geometria reale. In questo modo se si desidera modificare le dimensioni, basta regolare le dimensioni della funzione scheletro e il resto della parte viene aggiornato di conseguenza.
[[Image:HolderTop2-2-1.jpg|La geometria scheletro|thumb|right|400px]]

<br clear=all>

<span id="The_main_body"></span>
== Il corpo principale ==

[[Image:HolderTop2-3.jpg|Schizzo della prima estrusione|thumb|right|400px]]
Creare un nuovo corpo e renderlo attivo. Lo schizzo della prima estrusione è mostrato a destra. Esso è posto su un piano di riferimento, con un offset di 5 mm (lo spessore della parete) dalla faccia che nello scheletro definisce un fianco (esterno) di uno degli anelli di tenuta del cuscinetto. Poiché tutte le dimensioni importanti sono prese dallo scheletro, ci sono solo tre dimensioni: l'entità della lavorazione (3 mm) alla base come offset per il piano XY, lo spessore della parete 5 mm dal diametro esterno dello scheletro, e i 2 gradi dell'angolo di sformo. Per creare la dimensione 5 mm, è necessario prima selezionare il cerchio esterno (raggio 45 mm) della geometria scheletro come "geometria esterna" dello schizzo, e poi aggiungere una linea di costruzione tangente e vincolata a questo cerchio con un angolo di due gradi.

Probabilmente vi starete chiedendo perché c'è questo piccolo segmento dritto in fondo a ciascun arco. Questo segmento assicura che sarà possibile creare uno sformo con un angolo di 2 gradi sugli archi. Questo potrebbe sembrare un lavoro eccessivo per ottenere un vantaggio minimo, ma molti programmi CAD (e forse un giorno anche FreeCAD) dispongono di strumenti che evidenziono un modello solido in diversi colori e mostrano subito tutte le facce dove l'angolo di sformo non è corretto. Certamente non si vuole che al proprio modello accada questo, soprattutto dopo avervi aggiunto un sacco di raccordi!
<br clear=all>

[[Image:HolderTop2-4.jpg|La prima estrusione (Pad)|thumb|right|400px]]
Dopo aver finito il disegno (che è un po' complicato a causa delle linee tangenziali per lo sformo di 2 gradi), creare con questo schizzo una estrusione (Pad) che si estenda fino all'altro fianco della geometria dello scheletro, di nuovo con un offset dal fianco di 5 mm.  Questa volta non è necessario creare un piano di riferimento, la modalità "fino alla faccia" della finestra di dialogo dell'estrusione permette di inserire un offset.
<br clear=all>

[[Image:HolderTop2-5.jpg|Sketch per l'estrusione con cui si asporta del materiale|thumb|right|400px]]
Successivamente, si asporta un po' di materiale su entrambe le estremità del Pad, perché per i pezzi di fusione l'ideale è avere sempre uno spessore il più uniforme possibile. Creare uno schizzo su ciascuno dei lati frontali del Pad e dimensionarlo con 5 mm di offset dal cerchio che rappresenta l'anello di tenuta del cuscinetto (raggio 27,5 mm su un lato e 34 mm sull'altro). Per il segmento della linea di fondo del disegno, creare un'altra geometria esterna al Pad e vincolarla a questa. In questo modo lo schizzo ha una sola dimensione, 5 mm dello spessore della parete (le dimensioni 150 mm e 75 mm non sono importanti, basta che siano abbastanza grandi in modo da garantire che tutto quello che non serve venga asportato).
<br clear=all>

[[Image:HolderTop2-6.jpg|Il Pad con gli scavi per ottenere uno spessore uniforme della parete|thumb|right|400px]]
Utilizzare il disegno è stato creato per eseguire uno scavo ed estenderlo alla faccia della geometria dello scheletro che rappresenta il cuscinetto, meno 5 mm di offset per lo spessore della parete. Per il secondo scavo, è possibile utilizzare l'opzione "Duplica oggetto selezionato" dal menu Modifica per duplicare il disegno già fatto (scegliere di non duplicare gli oggetti dipendenti se viene posta la domanda). Quindi, selezionare la faccia su cui si desidera spostare questo schizzo, e dire a FreeCAD di mappare lo schizzo su questa faccia (questa è una voce del menu PartDesign). Dopo aver creato il secondo scavo, è possibile osservare il risultato dal basso per verificare se si dispone di una parete di spessore di 5 mm intorno al contorno della geometria dello scheletro.
<br clear=all>

[[Image:HolderTop2-7.jpg|Piano neutro per applicare lo sformo|thumb|right|400px]]
Ora è il momento di creare gli sformi e i raccordi. L'operazione di sformo richiede un piano neutro, questo significa che la geometria che è tagliata da questo piano rimarrà al suo posto, mentre il resto della faccia viene inclinato secondo l'angolo di sformo. Usare il piano della base del Pad come piano neutro non è una buona idea poiché lo spessore della parete nella parte superiore del supporto diventerebbe meno di 5 mm. Quindi per questa operazione creiamo un piano di Riferimento con un offset di circa 35 mm da XY. Attivare il corpo Scheletro e creare lì il piano, perché ne avremo ancora bisogno per applicare degli sformi ad altri corpi.
<br clear=all>

[[Image:HolderTop2-8.jpg|Primo corpo con sformi e raccordi|thumb|right|400px]]
L'immagine a destra mostra il primo corpo finito con gli sformi e i raccordi applicati. Notare che i bordi esterni (concavo) hanno un raggio di raccordo maggiore di 5 mm, sempre con lo scopo di creare uno spessore della parete il più uniforme possibile (più di 5 mm non è possibile perché altrimenti dopo la lavorazione interna del supporto lo spessore della parete diventa inferiore a 5 mm).
<br clear=all>

<span id="Adding_the_bodies_for_the_bolts"></span>
== Aggiungere i corpi per i bulloni ==

[[Image:HolderTop2-13.jpg|Sketch con il disegno della parte per i bulloni|thumb|right|400px]]
I bulloni hanno bisogno di due corpi cilindrici su entrambi i lati del corpo principale. E' meglio inserire lo sformo di 2 gradi nel disegno. Ho provato a creare un cilindro con una rotazione e applicarvi successivamente uno sformo, ma dopo il mirroring sono successe delle strane cose e non ho potuto applicarvi i raccordi, perché la superficie era in qualche modo deformata.

Lo schizzo è dimensionato in modo che l'asse di rotazione sia distante 12 mm dal diametro esterno del corpo scheletro, 7 mm per il raggio del foro più 5 mm per lo spessore della parete. Per il gusto di avere una parte completamente parametrica è una buona idea aggiungere un piano allo scheletro a circa 25 mm sopra il piano XY per contrassegnare la faccia superiore dei cilindri. Dato che questa faccia verrà lavorata, lo schizzo è dimensionato 3 mm al di sopra di essa.

<br clear=all>

[[Image:HolderTop2-14.jpg|I corpi per i bulloni|thumb|right|400px]]
Creare una rivoluzione dallo schizzo e applicare un raccordo di 4 mm al bordo superiore. In questo modo, dopo la lavorazione in cui si asportano 3 mm, rimane ancora un lieve raccordo che permette di evitare che il bordo sia tagliente e che qualcuno possa ferirsi durante il serraggio dei bulloni.
<br clear=all>

[[Image:HolderTop2-16.jpg|Il corpo principale con i due corpi per i bulloni|thumb|right|400px]]
Creare una funzione booleana per fondere il corpo principale con il corpo per il bullone. Quindi creare un nuovo corpo per l'altro lato. Duplicare lo schizzo della rivoluzione, spostarlo in questo corpo e creare il secondo corpo per i bulloni (il mirroring di un corpo non è ancora supportato, quindi è necessario rifarlo per la maggior parte). Poi fondere anche questo secondo corpo nel corpo principale. Infine applicare un grande raccordo sul bordo creato con l'operazione di fusione booleana, il bordo tra il corpo principale e il corpo per i bulloni. Il più grande che ho potuto ottenere è di 4 mm.
<br clear=all>

<span id="Hollowing_out_the_main_body"></span>
== Scavare il corpo principale ==

[[Image:HolderTop2-9.jpg|Il primo Pad del corpo dello scavo all'interno del corpo principale|thumb|right|300px]]
Passare ora a lavorare sulla parte interna del supporto e scavare per creare lo spazio per il cuscinetto e per gli anelli di tenuta. Nel fare questo, naturalmente, bisogna tenere a mente il sovrametallo di 3 mm. Dal momento che questo tutorial insegna il metodo "multi-corpo", prima si crea la geometria interna come un corpo separato e poi la si aporta dal corpo principale con una operazione booleana.

Creare un nuovo corpo e renderlo attivo. In primo luogo, serve un piano di riferimento con un offset di 3 mm all'interno della faccia scheletro che rappresenta il lato del cuscinetto. Poi, duplicare il disegno del primo pad del corpo principale. Sarà aggiunto al corpo principale, quindi fare clic destro su di esso e scegliere di spostarlo sul corpo appena creato (se è attivo l'ambiente PartDesign, questa opzione è disponibile solo nel menu di contesto). Mappare il disegno su piano di riferimento (se dopo la mappatura lo schizzo risulta capovolto, spostare il piano di riferimento sull'altro lato del cuscinetto, accanto a cui si trova lo schizzo duplicato). Ora, modificare il disegno in modo che il diametro sia di 3 mm inferiore al diametro esterno della geometria scheletro che rappresenta il cuscinetto. Basta rimuovere la dimensione di 5 mm, trascinare il disegno all'interno del cerchio di riferimento, e poi creare una nuova dimensione di 3 mm.
<br clear=all>

[[Image:HolderTop2-10.jpg|Il corpo dello scavo interno al corpo scheletro|thumb|right|400px]]
Ora servono altri due Pad per scavare lo spazio per gli anelli di tenuta. Duplicare il disegno del primo pad del "Corpo per lo scavo" e mapparlo al piano XZ. Modificare lo schizzo e sostituire il riferimento esterno con il diametro esterno dell'anello di tenuta del cuscinetto. Estrudere questo schizzo con un offset di 3 mm dal fianco dell'anello di tenuta. Ripetere l'intero processo per l'anello di tenuta del lato opposto.

Dopo di questo creare altri due rilievi all'interno del supporto, come gli ultimi due per dare un gioco all'albero (ad esempio 3 mm).
<br clear=all>

[[Image:HolderTop2-11.jpg|Il corpo completo della parte da asportare (meno i raccordi impossibili)|thumb|right|400px]]
Ora non rimane che applicare lo sformo alle facce piane laterali, utilizzando lo stesso piano neutro come si è fatto per il corpo principale, e i raccordi. Applicare un raccordo generale di 3 mm a tutti i bordi. Noterete che ci sono diversi spigoli che non possono essere raccordati ... questo è un difetto del kernel geometrico sottostante usato da FreeCAD.
<br clear=all>

[[Image:HolderTop2-15.jpg|La parte grezza completata del supporto (senza le lavorazioni)|thumb|right|400px]]
Siamo pronti per "svuotare" il corpo principale. Selezionarlo e scegliere di creare una nuova operazione booleana. Aggiungere il corpo della parte da asportare alla lista della finestra e impostare l'operazione "Differenza". Mettere un raccordo di 3 mm sui due bordi derivanti dalla operazione di asportazione (rimangono di nuovo alcuni bordi che "non sono raccordabili"). Il risultato dovrebbe essere simile alla figura sulla destra.

Ora la parte grezza è completata. Questo è ciò a cui il supporto somiglierà prima della lavorazione. Si noti che, poiché lo stampo avrà una metà superiore e metà una inferiore, il bordo tra queste due parti può non essere raccordato. Inoltre, se si cede questo modello a una fonderia ricordarsi di sottolineare che esso ha le dimensioni che deve avere dopo il getto. La fonderia dovrà poi applicare una certa percentuale di restringimento al modello (rendendo il modello digitale utilizzato per fabbricare lo stampo più grande in modo che dopo la fusione, quando il metallo si raffredda e si contrae, abbia il giusto formato).
<br clear=all>

<span id="Machining"></span>
== Lavorazione ==

[[Image:HolderTop2-17.jpg|Sketch per praticare il foro per le viti|thumb|right|400px]]
Per togliere il materiale della lavorazione dall'interno del supporto, si può usare molto convenientemente il Corpo Scheletro stesso. Se non si vuole fare questo perché dopo lo scheletro viene nascosto da qualche parte nell'albero della struttura, è anche possibile duplicare lo schizzo della funzione di rivoluzione dello scheletro e ricreare la rivoluzione in un nuovo corpo. Questo, però, non è completamente parametrico, perché il disegno duplicato è indipendente da quello originale, in questo modo se si cambia una dimensione si deve poi lavorare su entrambi i disegni. Le funzioni duplicate dipendenti saranno supportate in futuro.

Per il resto della lavorazione, creare un nuovo corpo. La parte inferiore del supporto viene lavorato da un pad disegnato sul piano xy e esteso verso il basso. Successivamente, disegnare una rivoluzione per fare un foro per i bulloni. E' necessario fare il disegno sul piano XZ e ruotarlo in modo da poter utilizzare il diametro esterno del corpo scheletro come riferimento esterno. La parte superiore del disegno servirà a lavorare una superficie piana per la testa del bullone. Esso è dimensionato per lasciare almeno 5 mm di spessore nella parete del supporto. Se questo non lascia abbastanza spazio per la testa del bullone allora si può spostare verso l'alto il piano di Riferimento. Naturalmente, si potrebbe mettere questa logica nello scheletro, ma questo viene lasciato come esercizio per il lettore!
<br clear=all>

[[Image:HolderTop2-18.jpg|Il corpo della lavorazione|thumb|right|400px]]
È possibile eseguire il mirroring della rivoluzione sugli assi YZ. L'immagine a destra mostra il "Corpo lavorazione". Naturalmente, la maggior parte delle dimensioni dei Pad e delle Rivoluzioni non sono importanti finché vi è abbondanza di sovrapposizione.
<br clear=all>

[[Image:HolderTop2-19.jpg|Il supporto finito con le lavorazioni|thumb|right|400px]]
Infine, creare una operazione booleana per asportare il Corpo lavorazione dal Corpo principale. Se si desidera un piacevole effetto visivo, è possibile colorare le superfici lavorate in modo diverso dal resto del pezzo. Questo costituisce anche un utile controllo visivo per individuare eventuali lavorazioni dimenticate.
<br clear=all>

== Parte Uno == 
[[PartDesign Bearingholder Tutorial I/it|Tutorial di PartDesign Supporto per cuscinetto I]]


[[Category:Tutorials{{#translation:}}]]
{{clear}}