import FreeCAD as App
import Part
from FreeCAD import Vector

# -----------------------------------------------------
# ROTATING EYE BOLT PARAMETERS
# -----------------------------------------------------
total_length   = 183.0     # mm
rod_dia        = 20.0      # mm
stud_length    = 40.0      # mm
eye_inner_len  = 82.0      # mm
eye_inner_wid  = 39.83     # mm
eye_thickness  = 20.0      # mm
eye_wall       = 20.0      # mm
color          = (0.0, 1.0, 1.0)   # Aqua Blue (R,G,B)

# -----------------------------------------------------
# CREATE NEW DOCUMENT
# -----------------------------------------------------
doc = App.newDocument("Rotating_Eye_Bolt")

# -----------------------------------------------------
# BUILD THE EYE RING (ELLIPTICAL)
# -----------------------------------------------------
a_inner = eye_inner_len / 2
b_inner = eye_inner_wid / 2
a_outer = a_inner + eye_wall
b_outer = b_inner + eye_wall

outer_ellipse = Part.Ellipse(Vector(0,0,0), Vector(a_outer,0,0), Vector(0,b_outer,0))
inner_ellipse = Part.Ellipse(Vector(0,0,0), Vector(a_inner,0,0), Vector(0,b_inner,0))

outer_face = Part.Face(Part.Wire(outer_ellipse.toShape()))
inner_face = Part.Face(Part.Wire(inner_ellipse.toShape()))
eye_face   = outer_face.cut(inner_face)
eye_solid  = eye_face.extrude(Vector(0,0,eye_thickness))

# -----------------------------------------------------
# BUILD THE ROD (CYLINDER)
# -----------------------------------------------------
rod_radius = rod_dia / 2
rod_length = total_length - eye_thickness
rod = Part.makeCylinder(rod_radius, rod_length)

# -----------------------------------------------------
# ASSEMBLE (rod + eye)
# -----------------------------------------------------
eye_solid.translate(Vector(0,0,rod_length))
bolt = rod.fuse(eye_solid)

# -----------------------------------------------------
# ADD TO DOCUMENT & COLOR
# -----------------------------------------------------
obj = doc.addObject("Part::Feature", "Rotating_Eye_Bolt")
obj.Shape = bolt
obj.ViewObject.ShapeColor = color
App.ActiveDocument.recompute()

# -----------------------------------------------------
# EXPORT TO STEP (AutoCAD-compatible)
# -----------------------------------------------------
out_path = App.getUserAppDataDir() + "Rotating_Eye_Bolt.step"
Part.export([obj], out_path)

print("✅ STEP file created at:", out_path)
print("Open in AutoCAD → File → Import → STEP → Save As DWG.") [[Special:Contributions/103.228.144.203|103.228.144.203]] 10:57, 3 November 2025 (UTC)