<languages/>

{{TutorialInfo/pl
|Class=Modelowanie
|Topic=Tworzenie pary kół zębatych stożkowych
|Level=Zaawansowany
|Time= Do uzupełnienia
|Author=[[User:FBXL5|FBXL5]]
|FCVersion=1.1
|SeeAlso= [[Gear_Workbench/pl|środowisko pracy Koła zębate]]
}}

<span id="Introduction"></span>
==Wprowadzenie==

Poradnik '''Koła stożkowe''' opisuje, jak zebrać wymagane dane do utworzenia pary kół stożkowych za pomocą narzędzia [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/pl|Koło stożkowe]] ze [[Image:FCGear_workbench_icon.svg|16px]] [[Gear_Workbench/pl|środowiska pracy Koła zębate]] w kontekście [[Image:Workbench PartDesign.svg|16px]] [[PartDesign_Workbench/pl|środowiska Projekt Części]].

[[Image:BevelGears_Example00.png|300px]]

{{Caption|Para zazębionych kół stożkowych}}

Koło stożkowe może być budowane albo od okręgu podziałowego, albo od (podziałowego) wierzchołka, jego wirtualnego czubka, w zależności od właściwości '''reset_origin'''. W kolejnych krokach tego poradnika będziemy musieli przeskalować koło stożkowe, zachowując jego wierzchołek na miejscu, dlatego odznaczymy tę właściwość. 

<span id="Requirements"></span>
==Wymagania==

Narzędzie [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/pl|Koło stożkowe]] domyślnie tworzy koło stożkowe dla osi prostopadłych i przełożenia 1 : 1. Dla innych kątów między osiami, lepiej znanych jako kąty wałów, oraz różnych przełożeń musimy wyznaczyć odpowiedni kąt stożka podziałowego dla obu sparowanych kół stożkowych. Dodatkowo musimy dostosować wartości bazowe oraz wyprowadzić średnice podziałowe. 

<span id="Basic_Values"></span>
===Wartości podstawowe===

Zakładając, że solidnie wysililiśmy umysł, biorąc pod uwagę dostępną przestrzeń, obciążenia, przełożenie i kąt wałów, i wyznaczyliśmy następujące wartości bazowe:
: Moduł: <math>m = 2 mm</math>
: Przełożenie: <math>5 : 3</math>
: Kąt wałów: <math>\Sigma = 60^\circ</math>

<span id="Number_of_Teeth"></span>
===Liczba zębów===

Aby nie przeciążać naszych procesorów, ustawimy liczbę zębów (z) mniejszego koła na zaledwie {{Value|9}}, a tym samym liczbę zębów większego na {{Value|15}} (<math>15 : 9</math> odpowiada <math>5 : 3</math>).
: <math>z_1 = 15</math> (dla '''koła stożkowego 1''')
: <math>z_2 = 9</math> (dla '''koła stożkowego 2''')

<span id="Pitch_Diameter"></span>
===Średnica podziałowa===

Teraz możemy obliczyć średnice podziałowe (d):
: <math>d_1 = z_1 \cdot m = 15 \cdot 2 mm = 30 mm</math>
: <math>d_2 = z_2 \cdot m = 9 \cdot 2 mm = 18 mm</math>

<span id="Cone_Angles"></span>
===Kąty stożków===

Teraz kolej na FreeCAD, aby wyznaczył kąty stożków podziałowych (δ):
# Utwórz [[Image:Std_New.svg|16px]] [[Std_New/pl|nowy dokument]].
# Utwórz [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/pl|Zawartość]] ('''Zawartość''').
# Utwórz [[Image:Sketcher_NewSketch.svg|16px]] [[PartDesign_NewSketch/pl|Szkic]].

Używamy szkicu do narysowania 2 połączonych trójkątów, których osie symetrii są prostopadłe do boków reprezentujących średnice podziałowe. Oprócz kilku ukrytych więzów współliniowości i symetrii stosujemy dwa wiązania długości dla średnic podziałowych oraz wiązanie kątowe dla kąta wałów, aby całkowicie ustalić szkic, a następnie możemy użyć dwóch wiązań odniesienia do uzyskania obu kątów stożków podziałowych (i opuścić szkic):

[[Image:BevelGears_Example01.png|300px]]

{{Caption|Czerwony: ustalony kąt wałów oraz obie średnice podziałowe.<br>Niebieski: wynikowe kąty stożków podziałowych}}

Mamy teraz kąty stożków podziałowych:
: <math>\delta_1 = 38.21^\circ</math>
: <math>\delta_2 = 21.79^\circ</math>

<span id="Raw_Gears"></span>
==Czyste koła==

Jesteśmy gotowi do utworzenia pary kół stożkowych.

<span id="Bevel_Gear_1"></span>
===Koło stożkowe 1===

# Utwórz nową [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/pl|Zawartość środowiska Projekt Części]] ('''Body001''').
# Wywołaj polecenie [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/pl|Koło stożkowe]].
# Koło stożkowe ('''BevelGear''') zostaje utworzone natychmiast, z jego bokiem średnicy podziałowej stykającym się z początkiem układu współrzędnych i oczekujące na dostosowanie.
# W [[Property_View/pl|Widoku właściwości]] dostosuj następujące właściwości koła stożkowego:
## Ustaw {{PropertyData|module}} na {{Value|2 mm}}.
## Ustaw {{PropertyData|num_teeth}} na {{Value|15}}.
## Ustaw {{PropertyData|pitch_angle}} na {{Value|38.21°}} (dwie cyfry po przecinku są w zupełności wystarczające).
## Odznacz właściwość {{PropertyData|reset_origin}}, aby umieścić wierzchołek koła stożkowego w początku układu współrzędnych (spowoduje to odwrócenie koła stożkowego do góry nogami).
# Użyj [[Image:Std_TransformManip.svg|16px]] [[Std_TransformManip/pl|Std: Przemieszczenie]] do obrócenia koła stożkowego wokół początku układu współrzędnych tak, aby jego powierzchnia po stronie średnicy podziałowej była równoległa do poziomej linii szkicu reprezentującej tę samą średnicę podziałową większego koła (jeśli wartości zostały poprawnie wpisane, linia powinna być współpłaszczyznowa z powierzchnią).

[[Image:BevelGears_Example02.png|300px]]

{{Caption|Koło stożkowe 1 prawidłowo spozycjonowane}}

<span id="Bevel_Gear_2"></span>
===Koło stożkowe 2===

# Utwórz kolejną nową [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/pl|Zawartość środowiska Projekt Części]] ('''Body002''').
# Wywołaj polecenie [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/pl|Koło stożkowe]].
# Koło stożkowe ('''BevelGear002''') zostaje utworzone.
# W [[Property_View/pl|Widoku właściwości]] dostosuj następujące właściwości koła stożkowego:
## Ustaw {{PropertyData|module}} na {{Value|2 mm}}.
## Ustaw {{PropertyData|num_teeth}} na {{Value|9}}.
## Ustaw {{PropertyData|pitch_angle}} na {{Value|21.79°}}.
## Odznacz właściwość {{PropertyData|reset_origin}}, aby umieścić wierzchołek koła stożkowego w początku układu współrzędnych (spowoduje to odwrócenie koła stożkowego do góry nogami).
# Użyj [[Image:Std_TransformManip.svg|16px]] [[Std_TransformManip/pl|Std: Przemieszczenie]] do obrócenia koła stożkowego wokół początku układu współrzędnych tak, aby jego powierzchnia po stronie średnicy podziałowej była równoległa do skośnej linii szkicu reprezentującej tę samą średnicę podziałową mniejszego koła (jeśli wartości zostały poprawnie wpisane, linia powinna ponownie być współpłaszczyznowa z powierzchnią).

[[Image:BevelGears_Example03.png|300px]]

{{Caption|Koło stożkowe 2 prawidłowo spozycjonowane}}

<div lang="en" dir="ltr" class="mw-content-ltr">
At this point both bevel gears should mesh with each other where their pitch cones meet in the initial sketch, but their shapes don't look like real bevel gears.
</div>

[[Image:BevelGears_Example04.png|300px]]

<div lang="en" dir="ltr" class="mw-content-ltr">
{{Caption|Meshing raw bevel gears}}
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
We notice that the [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear|BevelGear]] tool extended the pitch cone to become the face cone before cutting the teeth, but it has only built the bevel gear from the pitch circle toward the apex (the virtual tip), and ignored the back cone geometry in the opposite direction as shown in this section view of the finished bevel gear:
</div>

[[Image:BevelGears_Example14.png|300px]]

<div lang="en" dir="ltr" class="mw-content-ltr">
{{Caption|Green: Pitch cone,<br>Red: Face cone.<br>Blue: Back cone}}
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
To obtain a proper bevel gear we have to enlarge our raw bevel gears and cut off surplus geometry, but instead of cutting off we will intersect revolution objects defining the cross-sections with our to be enlarged raw bevel gears.
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
==Intersection Objects==
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
We have to define the desired cross-sections from their axes outwards, and then revolve them to create objects that will be intersected with the results of the steps above to result in a proper pair of bevel gears.
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
===Revolution Object 1===
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
# Activate the first body ('''Body''').
# Create another [[Image:Sketcher_NewSketch.svg|16px]] [[PartDesign_NewSketch|sketch]], and in the sketch:
## Project the lines representing the pitch diameters of our first sketch into our new sketch.
## Draw a construction line from their intersection point to the origin. (it is where the pitch cones meet, and its length is called cone distance).
## We need a closed wire of six straight lines:
### Draw one line collinear with the vertical sketch axis.
### Draw two lines parallel to the horizontal projection line to define position and thickness of the hub area.
### Draw two lines perpendicular to the construction line to define the width of the teeth, one is running through the intersection point and also defines the back cone.
### Draw one line closing the wire that is only required to run outside the raw bevel gear since that already has a correctly modeled teeth hight.
# Leave the sketch.
# Create another new [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body|PartDesign Body]] ('''Body003''').
# Use a [[Image:PartDesign_SubShapeBinder.svg|16px]] [[PartDesign_SubShapeBinder|Sub-Shape Binder]] to copy the sketch into the body.
# Create a [[Image:PartDesign_Revolution.svg|16px]] [[PartDesign_Revolution|Revolve]] object ('''Revolution''') from the sub-shape binder.
</div>

[[Image:BevelGears_Example05.png|300px]] [[Image:BevelGears_Example06.png|300px]]

<div lang="en" dir="ltr" class="mw-content-ltr">
{{Caption|Left: Sketch of cross-section.
Right: Resulting Revolution object 1}}
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
The width of the teeth (also called face width) is usually roughly one third of the cone distance (24.25° in this case), thus 8 mm was chosen for this example.
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
===Revolution Object 2===
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
# Activate the first body ('''Body''') again.
# Create another [[Image:Sketcher_NewSketch.svg|16px]] [[PartDesign_NewSketch|sketch]], and in the sketch:
## Project the lines representing the pitch diameters, and also the line representing the axis of our smaller bevel gear from our first sketch into our new sketch.
## Draw a construction line from their intersection point of the pitch diameters to the origin.
## We need a closed wire of six straight lines:
### Draw one line collinear with the projected axis.
### Draw two lines parallel to the oblique projected pitch diameter to define position and thickness of the hub area.
### Draw two lines perpendicular to the construction line to define the width of the teeth, one is running through the intersection point and also defines the back cone.
### Draw one line closing the wire that is only required to run outside the raw bevel gear since it already has a correctly modeled teeth hight.
# Leave the sketch.
# Create another new [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body|PartDesign Body]] ('''Body004''')..
# Use a [[Image:PartDesign_SubShapeBinder.svg|16px]] [[PartDesign_SubShapeBinder|Sub-Shape Binder]] to copy the sketch into the body.
# Create a [[Image:PartDesign_Revolution.svg|16px]] [[PartDesign_Revolution|Revolve]] object ('''Revolution001''') from the sub-shape binder.
</div>

[[Image:BevelGears_Example07.png|300px]] [[Image:BevelGears_Example08.png|300px]]

<div lang="en" dir="ltr" class="mw-content-ltr">
{{Caption|Left: Sketch of cross-section.
Right: Resulting Revolution object 2}}
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
==Finished Bevel Gears==
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
Now we will intersect the raw bevel gears with the revolution objects to find their common shapes. Having hidden all objects but our raw bevel gears and revolution objects, we will notice that the gears do not protrude enough from the revolution object. Since we built the bevel gears from the apex we can (mis-) use the module value to "scale" the gear and adjust its height before intersecting.
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
===Bevel Gear 1===
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
# Activate bevel gear 1 ('''Body001''').
# In the [[Property_View|Property View]] adjust these properties of the bevel gear:
## Set the {{PropertyData|module}} property to {{Value|2.5 mm}}.
## Set the {{PropertyData|height}} property to {{Value|15 mm}}.
# Press the {{Button|[[Image:Std_Refresh.svg|16px]] [[Std_Refresh|Recompute]]}} button to see the changes.
# invoke [[Image:PartDesign_Boolean.svg|16px]] [[PartDesign_Boolean|PartDesign Boolean Operation]].
# The '''Boolean Parameters''' dialog opens in the [[Task_Panel|Task Panel]]:
#* Press the {{Button|Add Body}} button
#* Select the revolution object 1 ('''Body003''').
#* Press the {{Button|Add Body}} button again to finish the selection.
#* Select '''Common''' from the options below the list.
# Press the {{Button|OK}} button to shut the dialog and finish the operation.
# The shape of bevel gear 1 is finished.
</div>

[[Image:BevelGears_Example09.png|300px]] [[Image:BevelGears_Example10.png|300px]]

<div lang="en" dir="ltr" class="mw-content-ltr">
{{Caption|Left: Enlarged raw bevel gear 1 and revolution object 1.
Right: Resulting finished bevel gear 1}}
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
===Bevel Gear 2===
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
# Activate bevel gear 2 ('''Body002''').
# In the [[Property_View|Property View]] adjust these properties of the bevel gear:
## Set the {{PropertyData|module}} property to {{Value|2.5 mm}}.
## Set the {{PropertyData|height}} property to {{Value|15 mm}}.
# Press the {{Button| [[Image:Std_Refresh.svg|16px]] [[Std_Refresh|Recompute]]}} button to see the changes.
# Invoke [[Image:PartDesign_Boolean.svg|16px]] [[PartDesign_Boolean|PartDesign Boolean Operation]].
# The '''Boolean Parameters''' dialog opens in the [[Task_Panel|Task Panel]]:
#* Press the {{Button|Add Body}} button
#* Select the revolution object 2 ('''Body004''').
#* Press the {{Button|Add Body}} button again to finish the selection.
#* Select '''Common''' from the options below the list.
# Press the {{Button|OK}} button to shut the dialog and finish the operation.
# The shape of bevel gear 2 is finished.
</div>

[[Image:BevelGears_Example11.png|300px]] [[Image:BevelGears_Example12.png|300px]]

<div lang="en" dir="ltr" class="mw-content-ltr">
{{Caption|Left: Enlarged raw bevel gear 2 and revolution object 2.
Right: Resulting finished bevel gear 2}}
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
===Missing Features===
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
To pair two gears we usually use the pitch circle, or we could optionally use the apex in connection with the axis, but the problem is that neither the pitch circle nor the apex is represented by a geometric element of the final shape and thus cannot be selected directly. To position the gears in an assembly we have to add/use selectable auxiliary geometry that can be shown/hidden on demand, or use existing shape elements that have a known offset from the pitch circle/apex and enter an offset value manually.
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
==What is Left to do?==
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
Now we have two decent bevel gears but they cannot be mounted to axles or shafts, They have to be extended with some shape elements, either cylindric ones for bearings to be able to rotate around an axle, or prismatic ones to be able to transmit torque into a shaft.
</div> 

<div lang="en" dir="ltr" class="mw-content-ltr">
Such additions are quite simple to model so that they are not covered by this tutorial.
</div>

<div lang="en" dir="ltr" class="mw-content-ltr">
We could add a support object and create an animated assembly, but this as well is another topic for another tutorial.
</div>

[[Image:BevelGears_Example13.gif|300px]]