{{Page in progress}}

{{TutorialInfo/pl
|Topic=Modelowanie
|Level=Użytkownik zaawansowany
|Author=NormandC
|Time= nieokreślony
|FCVersion=0.19.23300 lub nowszy
|Files=brak
}}

{{VeryImportantMessage|Ten poradnik został pierwotnie napisany dla przestarzałej wersji rozwojowej FreeCAD. Od kwietnia 2016 r. funkcje te zostały zintegrowane w wersji 0.17 pre-development dostępnej [https://github.com/FreeCAD/FreeCAD/releases/tag/0.17_pre w serwisie GitHub].
<br>
Należy pamiętać, że ta wersja FreeCAD jest wciąż na wczesnym etapie rozwoju. Ponadto poradnik ten może wymagać aktualizacji. Jeśli chcesz wziąć udział w jego przeglądzie i aktualizacji, napisz w sekcji Wiki na [https://forum.freecad.org/viewforum.php?style=4&f=21 forum].}}

[[Image:HolderTop2-19.jpg|Poradnik dotyczący oprawki łożyska - Gotowa oprawka łożyska ''(góra)''|thumb|right|400px]]

<strike>  
Jak wskazuje ostrzeżenie na górze strony, ten '''samouczek NIE ZADZIAŁA, chyba że skompilujesz specjalną, wysoce eksperymentalną gałąź kodu źródłowego FreeCAD''' i jest to wprowadzający samouczek do modelowania w środowisku pracy Projekt Części w FreeCAD '''z użyciem płaszczyzn konstrukcyjnych, które są funkcją jeszcze niedostępną w większości wersji FreeCAD'''.  
</strike>

==Cel w skrócie==
Celem tego samouczka jest wprowadzenie Cię do dwóch różnych sposobów pracy przy tworzeniu odlewanego elementu z pochyleniami i zaokrągleniami. W zależności od tego, z jakimi innymi programami CAD miałeś do czynienia, jeden z tych sposobów może być Ci już znany. Jako przykład praktyczny będziemy modelować prosty uchwyt łożyska.

To jest druga część samouczka. Będzie ona wykorzystywać to, co można nazwać podejściem 'wielobryłowym' na przykładzie (prostszej) górnej części uchwytu.

Oczywiście, aby przejść przez ten poradnik należy aktywować środowisko pracy Projekt Części.

<strike>Możesz znaleźć moją wersję elementu stworzonego w tym samouczku [[http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4 tutaj]]</strike> ''Plik nie jest już dostępny, nowy zostanie udostępniony w późniejszym terminie''. <br clear=all>

<span id="Design_data"></span>
==Dane projektowe==

Uchwyt powinien być w stanie pomieścić łożysko o średnicy 90 mm i szerokości do 33 mm (np. typ DIN 630 2308, które ma średnicę wewnętrzną 40 mm). Łożysko wymaga w uchwycie (i na wale) kołnierza o wysokości co najmniej 4,5 mm. Górna część uchwytu będzie przykręcona do dolnej dwoma śrubami M12. Głowa takiej śruby wymaga co najmniej 20 mm wolnej przestrzeni. Po obu stronach łożyska powinna znajdować się rowek umożliwiający zamocowanie standardowego pierścienia uszczelniającego wał DIN 3760: 38x55x7 lub 40x55x7 po jednej stronie, 50x68x8 po drugiej stronie.

Uchwyt będzie odlewem piaskowym o minimalnej grubości ścianki 5 mm, kącie pochylenia 2 stopni oraz minimalnym promieniu zaokrąglenia 3 mm.

<br clear=all>

<span id="Setting_up_the_skeleton_geometry"></span>
== Ustawienie szkieletu geometrii ==

[[Image:HolderTop2-2.png|Szkic szkieletu geometrii|thumb|right|400px]]
Utwórz nowy element w środowisku pracy Projekt Części. Zmień nazwę domyślnie tworzonej Zawartości na Szkielet. Ta Zawartość prawdopodobnie jest już aktywowana, co można zobaczyć po niebieskim tle w drzewku funkcji. Utwórz nowy szkic na płaszczyźnie YZ, zawierający zarys wału, łożyska i pierścieni uszczelniających. Po zakończeniu szkicu utwórz z niego cechę obrócenia. Ta funkcja szkieletu będzie później używana jako odniesienie dla rzeczywistej geometrii. Oznacza to, że jeśli będziesz chciał zmienić jakiekolwiek wymiary, wystarczy dostosować wymiary funkcji szkieletu, a reszta elementu zostanie odpowiednio zaktualizowana.
[[Image:HolderTop2-2-1.jpg|Szkielet geometrii|thumb|right|400px]]

<br clear=all>

<span id="The_main_body"></span>
== Główna Zawartość==

[[Image:HolderTop2-3.jpg|Szkic pierwszego wyciągnięcia|thumb|right|400px]]
Utwórz nową Zawartość i aktywuj ją. Szkic pierwszego wyciągnięcia pokazano po prawej stronie. Został on umieszczony na płaszczyźnie datum z odsunięciem 5 mm (grubość ścianki) od powierzchni szkieletu wyznaczającej stronę jednego z pierścieni uszczelniających łożyska. Ponieważ wszystkie ważne wymiary są pobierane ze szkieletu, są tylko trzy wymiary: zapas obróbkowy (3 mm) u podstawy jako odsunięcie od płaszczyzny XY, 5 mm grubości ścianki od średnicy zewnętrznej szkieletu oraz kąt nachylenia (draft) 2 stopnie. Aby utworzyć wymiar 5 mm, należy najpierw wybrać zewnętrzny okrąg (promień 45 mm) szkieletu geometrii jako geometrię zewnętrzną w szkicowniku, a następnie wstawić linię konstrukcyjną ograniczoną stycznie do tego okręgu i pod kątem dwóch stopni.

Pewnie zastanawiasz się, dlaczego na dole każdego łuku znajduje się ten mały prosty odcinek. Odcinek ten zapewnia, że na łukach będzie zachowany kąt pochylenia 2 stopnie. Może się to wydawać dużo pracy dla niewielkiej korzyści, ale wiele programów CAD (a być może kiedyś również FreeCAD) posiada narzędzia, które podświetlają model bryłowy różnymi kolorami i od razu pokazują wszystkie powierzchnie, na których kąt nachylenia nie jest prawidłowy. Nie chcesz, aby coś takiego stało się z Twoim modelem, zwłaszcza po dodaniu wielu zaokrągleń!
<br clear=all>

[[Image:HolderTop2-4.jpg|Pierwsze wyciągnięcie|thumb|right|400px]]
Po ukończeniu szkicu (co może być nieco trudne z powodu stycznych linii pod kątem 2 stopni) utwórz z niego wyciągnięcie rozciągające się do drugiej strony szkieletu geometrii, ponownie z odsunięciem 5 mm od powierzchni bocznej. Tym razem nie trzeba tworzyć płaszczyzny konstrukcyjnej — tryb "do powierzchni" w oknie dialogowym wyciągnięcia pozwala wprowadzić odsunięcie.
<br clear=all>

[[Image:HolderTop2-5.jpg|Szkic do wycięcia przez wyciągnięcie|thumb|right|400px]]
Następnie usuniemy trochę materiału na obu końcach wyciągnięcia, ponieważ w przypadku odlewów zawsze najlepiej jest, gdy grubość ścianki jest możliwie jak najbardziej jednolita. Utwórz szkic na każdej z końcowych powierzchni wyciągnięcia i wymiaruj go z odsunięciem 5 mm od koła reprezentującego pierścień uszczelniający łożyska (promień 27,5 mm po jednej stronie i 34 mm po drugiej). Dla dolnego odcinka linii szkicu utwórz kolejną geometrię zewnętrzną z wyciągnięcia i ogranicz do niej szkic. W ten sposób szkic ma tylko jeden wymiar, czyli grubość ścianki 5 mm (wymiary 150 mm i 75 mm nie są istotne, dopóki są wystarczająco duże, aby zapewnić wycięcie całego materiału). 
<br clear=all>

[[Image:HolderTop2-6.jpg|Wyciągnięcie z wycięciami w celu uzyskania jednolitej grubości ścianki|thumb|right|400px]]
Użyj utworzonego szkicu, aby wykonać Kieszeń i przedłuż ją do powierzchni geometrii szkieletu reprezentującej łożysko, z odjęciem 5 mm na grubość ścianki. W przypadku drugiej Kieszeni możesz skorzystać z opcji "Duplikuj wybrany obiekt" w menu Edycja, aby skopiować już wykonany szkic (jeśli pojawi się pytanie, wybierz nie duplikować obiektów zależnych). Następnie wybierz powierzchnię, na którą chcesz przenieść szkic, i nakaż FreeCAD, aby przypisał szkic do tej powierzchni (jest to opcja w menu środowiska Projekt Części). Po utworzeniu drugiej Kieszeni możesz obejrzeć wynik od spodu, aby sprawdzić, czy grubość ścianki wokół konturu geometrii szkieletu wynosi jednolite 5 mm. 
<br clear=all>

[[Image:HolderTop2-7.jpg|Płaszczyzna neutralna do zastosowania pochylenia|thumb|right|400px]]
Teraz nadszedł czas na utworzenie pochyleń i zaokrągleń. Funkcja pochylenia wymaga płaszczyzny neutralnej, co oznacza, że geometria przecięta przez tę płaszczyznę pozostanie na swoim miejscu, podczas gdy reszta powierzchni zostanie pochylona pod zadanym kątem. Użycie do tego celu dolnej powierzchni wyciągnięcia nie jest dobrym pomysłem, ponieważ grubość ścianki w górnej części uchwytu stałaby się mniejsza niż 5 mm. Dlatego tworzymy płaszczyznę datum odsuniętą o około 35 mm od płaszczyzny XY. Aktywuj Zawartość ze szkieletem i utwórz tam płaszczyznę, ponieważ będziemy jej potrzebować także do zastosowania pochylenia do innych obiektów. 
<br clear=all>

[[Image:HolderTop2-8.jpg|Pierwsza Zawartość z zastosowanym pochyleniem i zaokrągleniami|thumb|right|400px]]
Obrazek po prawej stronie pokazuje ukończoną pierwszą Zawartość z zastosowanym pochyleniem i zaokrągleniami. Zauważ, że zewnętrzne (wklęsłe) krawędzie mają większy promień zaokrąglenia wynoszący 5 mm, ponownie w celu uzyskania bardziej jednolitej grubości ścianki (więcej niż 5 mm nie jest możliwe, ponieważ po obróbce wnętrza uchwytu grubość ścianki stałaby się mniejsza niż 5 mm). <br clear=all>

<span id="Adding_the_bodies_for_the_bolts"></span>
== Dodawanie zawartości dla śrub ==

[[Image:HolderTop2-13.jpg|Szkic dla Zawartości dla śrub|thumb|right|400px]]
Śruby wymagają dwóch cylindrycznych Zawartości po obu stronach głównej Zawartości. Najlepiej uwzględnić kąt pochylenia 2 stopni już w szkicu. Próbowałem obrócić cylinder, a potem zastosować pochylenie, ale po odbiciu lustrzanym działy się dziwne rzeczy i nie mogłem dodać zaokrągleń, ponieważ powierzchnia w jakiś sposób się zniekształciła.

The sketch is dimensioned so that the rotation axis is 12mm distance to the outer diameter of the skeleton Body, 7mm for the radius of the hole plus 5mm for the wall thickness. For the sake of having a fully parametric part, it is a good idea to add a plane to the Skeleton about 25mm above the XY-plane to mark the top of the cylinders. Since this will be machined, the sketch is dimensioned 3mm above it.

<br clear=all>

[[Image:HolderTop2-14.jpg|The body for the bolts|thumb|right|400px]]
Create a revolution from the sketch and apply a fillet of 4mm to the top. This means that after machining away 3mm, a slight radius will remain which helps to avoid a sharp edge where someone could cut their hand when tightening the bolt.
<br clear=all>

[[Image:HolderTop2-16.jpg|The main body with the two bodies for the bolts|thumb|right|400px]]
Create a boolean feature to fuse the main Body and the bolt body. Then create a new body for the other side. Duplicate the sketch of the revolution, move it to this body and create the second body for the bolts (mirroring a Body is not supported yet so you need to redo most of it). Then fuse this second body into the main Body as well. Finally, apply a large fillet on the edge created by the boolean fuse operation. The largest I could get was 4mm.
<br clear=all>

== Hollowing out the main body ==

[[Image:HolderTop2-9.jpg|The first Pad of the cut-out body inside the main body|thumb|right|300px]]
We will now work on the inside of the holder and hollow it out to make space for the bearing and sealing rings. When doing this of course we need to keep in mind the 3mm machining allowance. Since this tutorial teaches the multi-body method, we will create the inside geometry as a separate body and then cut it out of the main body with a boolean operation.

Create a new body and make it active. First, we need a datum plane offset 3mm inside the skeleton face that shows the side of the bearing. Then, duplicate the sketch of the first Pad of the main body. It will be added to the main body, so right-click on it and choose to move it to the newly created body (this option is only available in the context menu if the PartDesign workbench is active). Map the sketch onto the datum plane (if the sketch turns upside-down after mapping, move the datum plane to the other side of the bearing, next to where the duplicated sketch is located). Now, modify the sketch so that the diameter is 3mm less than the outer diameter of the skeleton geometry that represents the bearing. All you need to do is remove the 5mm dimension, drag the sketch inside the reference circle, and create a new 3mm dimension.
<br clear=all>

[[Image:HolderTop2-10.jpg|The cut-out body inside the skeleton body|thumb|right|400px]]
Next we want two more Pads to hollow out the place for the sealing rings. Duplicate the sketch of the first pad of the cut-out Body and map it to the XZ-plane. Edit the sketch and replace the external reference with the outer diameter of the bearing sealing ring. Extrude this sketch to an offset of 3mm of the side of the sealing ring. Repeat the whole process for the sealing ring on the other side.

After this we want to create two more Pads like the last two to give the shaft a clearance (e.g. 3mm) inside the holder.
<br clear=all>

[[Image:HolderTop2-11.jpg|The complete cut-out body (minus impossible fillets)|thumb|right|400px]]
Now all that remains is to apply draft to the planar side faces, using the same neutral plane as for the main body, and filleting. Apply a general fillet of 3mm to all edges. You will notice that there are several edges that cannot be filleted... this is a defect of the underlying geometric kernel which FreeCAD uses.
<br clear=all>

[[Image:HolderTop2-15.jpg|The completed raw part of the holder (without machining)|thumb|right|400px]]
We are ready to hollow out the main body. Select it and choose to create a new Boolean operation. Add the cut-out body to the list window and set the operation to "Cut". Put a 3mm fillet on the two edges resulting from the cut-out operation (again some edges remain that are "unfilletable"). The result should look like the picture on the right.

The raw part is now completed. This is what the holder will look like before machining. Note that since the mold will have a top and bottom half, the edge between these two cannot be filleted. Also, if you give away this model to a foundry make sure to point out that it has the dimensions after casting. The foundry will then have to apply a certain percentage of shrinkage to the model (making the digital model used to manufacture the mold larger so that when the metal cools down and shrinks after casting it will have the right size).
<br clear=all>

== Machining ==

[[Image:HolderTop2-17.jpg|Sketch to "drill" the hole for the bolts|thumb|right|400px]]
To take away the material for machining the inside of the holder, very conveniently we can use the Skeleton Body itself. If you don't want that because then the skeleton gets hidden somewhere deep in the tree, you can also duplicate the sketch of the skeleton Revolution feature and re-create the revolution in another body. This is not completely parametric, though, because the duplicated sketch is independent of the original, so you will have to work on both if you change a dimension. Dependent duplicated features might be supported in the future sometime.

For the rest of the machining, create a new Body. The bottom of the holder will be machined by a Pad sketched on the XY-plane extending downwards. Next, sketch a revolution to make a hole for the bolts. You will need to sketch on the XZ-plane and revolve it so that you can choose the outer diameter of the skeleton Body as an external reference. The top part of the sketch will serve to machine a flat place for the head of the bolt. It is dimensioned to leave at least 5mm wall thickness in the holder. If this does not give enough space for the bolt head then you can move the datum plane upwards. Of course, you could put this logic into the Skeleton, which is left as an exercise to the reader!
<br clear=all>

[[Image:HolderTop2-18.jpg|The machining Body|thumb|right|400px]]
You can mirror the revolution on the YZ-axis. The picture on the right shows the "machining" Body. Of course, most of the dimensions of the Pads and Revolutions are not important as long as there is plenty of overlap.
<br clear=all>

[[Image:HolderTop2-19.jpg|The finished Holder with machining|thumb|right|400px]]
Finally, create a boolean operation to cut the machining Body out of the main Body. If you want a nice visual effect, you can colour the machined surfaces differently from the rest of the part. This is also a useful optical feedback showing you whether you forgot to machine somewhere.
<br clear=all>

==Część pierwsza==
[[PartDesign_Bearingholder_Tutorial_I/pl|Poradnik: Projekt części, uchwyt łożyska cześć 1]]


[[Category:Tutorials{{#translation:}}]]
{{clear}}