{{Page in progress}}

{{TutorialInfo/pl
|Topic=Modelowanie
|Level=Użytkownik zaawansowany
|Author=NormandC
|Time= nieokreślony
|FCVersion=0.19.23300 lub nowszy
|Files=brak
}}

{{VeryImportantMessage|Ten poradnik został pierwotnie napisany dla przestarzałej wersji rozwojowej FreeCAD. Od kwietnia 2016 r. funkcje te zostały zintegrowane w wersji 0.17 pre-development dostępnej [https://github.com/FreeCAD/FreeCAD/releases/tag/0.17_pre w serwisie GitHub].
<br>
Należy pamiętać, że ta wersja FreeCAD jest wciąż na wczesnym etapie rozwoju. Ponadto poradnik ten może wymagać aktualizacji. Jeśli chcesz wziąć udział w jego przeglądzie i aktualizacji, napisz w sekcji Wiki na [https://forum.freecad.org/viewforum.php?style=4&f=21 forum].}}

[[Image:HolderTop2-19.jpg|Poradnik dotyczący oprawki łożyska - Gotowa oprawka łożyska ''(góra)''|thumb|right|400px]]

<strike>  
Jak wskazuje ostrzeżenie na górze strony, ten '''samouczek NIE ZADZIAŁA, chyba że skompilujesz specjalną, wysoce eksperymentalną gałąź kodu źródłowego FreeCAD''' i jest to wprowadzający samouczek do modelowania w środowisku pracy Projekt Części w FreeCAD '''z użyciem płaszczyzn konstrukcyjnych, które są funkcją jeszcze niedostępną w większości wersji FreeCAD'''.  
</strike>

==Cel w skrócie==
Celem tego samouczka jest wprowadzenie Cię do dwóch różnych sposobów pracy przy tworzeniu odlewanego elementu z pochyleniami i zaokrągleniami. W zależności od tego, z jakimi innymi programami CAD miałeś do czynienia, jeden z tych sposobów może być Ci już znany. Jako przykład praktyczny będziemy modelować prosty uchwyt łożyska.

To jest druga część samouczka. Będzie ona wykorzystywać to, co można nazwać podejściem 'wielobryłowym' na przykładzie (prostszej) górnej części uchwytu.

Oczywiście, aby przejść przez ten poradnik należy aktywować środowisko pracy Projekt Części.

<strike>Możesz znaleźć moją wersję elementu stworzonego w tym samouczku [[http://ubuntuone.com/39PTZ3Y3LUnmZzpZQPcJT4 tutaj]]</strike> ''Plik nie jest już dostępny, nowy zostanie udostępniony w późniejszym terminie''. <br clear=all>

<span id="Design_data"></span>
==Dane projektowe==

Uchwyt powinien być w stanie pomieścić łożysko o średnicy 90 mm i szerokości do 33 mm (np. typ DIN 630 2308, które ma średnicę wewnętrzną 40 mm). Łożysko wymaga w uchwycie (i na wale) kołnierza o wysokości co najmniej 4,5 mm. Górna część uchwytu będzie przykręcona do dolnej dwoma śrubami M12. Głowa takiej śruby wymaga co najmniej 20 mm wolnej przestrzeni. Po obu stronach łożyska powinna znajdować się rowek umożliwiający zamocowanie standardowego pierścienia uszczelniającego wał DIN 3760: 38x55x7 lub 40x55x7 po jednej stronie, 50x68x8 po drugiej stronie.

Uchwyt będzie odlewem piaskowym o minimalnej grubości ścianki 5 mm, kącie pochylenia 2 stopni oraz minimalnym promieniu zaokrąglenia 3 mm.

<br clear=all>

<span id="Setting_up_the_skeleton_geometry"></span>
== Ustawienie szkieletu geometrii ==

[[Image:HolderTop2-2.png|Szkic szkieletu geometrii|thumb|right|400px]]
Utwórz nowy element w środowisku pracy Projekt Części. Zmień nazwę domyślnie tworzonej Zawartości na Szkielet. Ta Zawartość prawdopodobnie jest już aktywowana, co można zobaczyć po niebieskim tle w drzewku funkcji. Utwórz nowy szkic na płaszczyźnie YZ, zawierający zarys wału, łożyska i pierścieni uszczelniających. Po zakończeniu szkicu utwórz z niego cechę obrócenia. Ta funkcja szkieletu będzie później używana jako odniesienie dla rzeczywistej geometrii. Oznacza to, że jeśli będziesz chciał zmienić jakiekolwiek wymiary, wystarczy dostosować wymiary funkcji szkieletu, a reszta elementu zostanie odpowiednio zaktualizowana.
[[Image:HolderTop2-2-1.jpg|Szkielet geometrii|thumb|right|400px]]

<br clear=all>

<span id="The_main_body"></span>
== Główna Zawartość==

[[Image:HolderTop2-3.jpg|Szkic pierwszego wyciągnięcia|thumb|right|400px]]
Utwórz nową Zawartość i aktywuj ją. Szkic pierwszego wyciągnięcia pokazano po prawej stronie. Został on umieszczony na płaszczyźnie datum z odsunięciem 5 mm (grubość ścianki) od powierzchni szkieletu wyznaczającej stronę jednego z pierścieni uszczelniających łożyska. Ponieważ wszystkie ważne wymiary są pobierane ze szkieletu, są tylko trzy wymiary: zapas obróbkowy (3 mm) u podstawy jako odsunięcie od płaszczyzny XY, 5 mm grubości ścianki od średnicy zewnętrznej szkieletu oraz kąt nachylenia (draft) 2 stopnie. Aby utworzyć wymiar 5 mm, należy najpierw wybrać zewnętrzny okrąg (promień 45 mm) szkieletu geometrii jako geometrię zewnętrzną w szkicowniku, a następnie wstawić linię konstrukcyjną ograniczoną stycznie do tego okręgu i pod kątem dwóch stopni.

Pewnie zastanawiasz się, dlaczego na dole każdego łuku znajduje się ten mały prosty odcinek. Odcinek ten zapewnia, że na łukach będzie zachowany kąt pochylenia 2 stopnie. Może się to wydawać dużo pracy dla niewielkiej korzyści, ale wiele programów CAD (a być może kiedyś również FreeCAD) posiada narzędzia, które podświetlają model bryłowy różnymi kolorami i od razu pokazują wszystkie powierzchnie, na których kąt nachylenia nie jest prawidłowy. Nie chcesz, aby coś takiego stało się z Twoim modelem, zwłaszcza po dodaniu wielu zaokrągleń!
<br clear=all>

[[Image:HolderTop2-4.jpg|Pierwsze wyciągnięcie|thumb|right|400px]]
Po ukończeniu szkicu (co może być nieco trudne z powodu stycznych linii pod kątem 2 stopni) utwórz z niego wyciągnięcie rozciągające się do drugiej strony szkieletu geometrii, ponownie z odsunięciem 5 mm od powierzchni bocznej. Tym razem nie trzeba tworzyć płaszczyzny konstrukcyjnej — tryb "do powierzchni" w oknie dialogowym wyciągnięcia pozwala wprowadzić odsunięcie.
<br clear=all>

[[Image:HolderTop2-5.jpg|Szkic do wycięcia przez wyciągnięcie|thumb|right|400px]]
Następnie usuniemy trochę materiału na obu końcach wyciągnięcia, ponieważ w przypadku odlewów zawsze najlepiej jest, gdy grubość ścianki jest możliwie jak najbardziej jednolita. Utwórz szkic na każdej z końcowych powierzchni wyciągnięcia i wymiaruj go z odsunięciem 5 mm od koła reprezentującego pierścień uszczelniający łożyska (promień 27,5 mm po jednej stronie i 34 mm po drugiej). Dla dolnego odcinka linii szkicu utwórz kolejną geometrię zewnętrzną z wyciągnięcia i ogranicz do niej szkic. W ten sposób szkic ma tylko jeden wymiar, czyli grubość ścianki 5 mm (wymiary 150 mm i 75 mm nie są istotne, dopóki są wystarczająco duże, aby zapewnić wycięcie całego materiału). 
<br clear=all>

[[Image:HolderTop2-6.jpg|Wyciągnięcie z wycięciami w celu uzyskania jednolitej grubości ścianki|thumb|right|400px]]
Użyj utworzonego szkicu, aby wykonać Kieszeń i przedłuż ją do powierzchni geometrii szkieletu reprezentującej łożysko, z odjęciem 5 mm na grubość ścianki. W przypadku drugiej Kieszeni możesz skorzystać z opcji "Duplikuj wybrany obiekt" w menu Edycja, aby skopiować już wykonany szkic (jeśli pojawi się pytanie, wybierz nie duplikować obiektów zależnych). Następnie wybierz powierzchnię, na którą chcesz przenieść szkic, i nakaż FreeCAD, aby przypisał szkic do tej powierzchni (jest to opcja w menu środowiska Projekt Części). Po utworzeniu drugiej Kieszeni możesz obejrzeć wynik od spodu, aby sprawdzić, czy grubość ścianki wokół konturu geometrii szkieletu wynosi jednolite 5 mm. 
<br clear=all>

[[Image:HolderTop2-7.jpg|Płaszczyzna neutralna do zastosowania pochylenia|thumb|right|400px]]
Teraz nadszedł czas na utworzenie pochyleń i zaokrągleń. Funkcja pochylenia wymaga płaszczyzny neutralnej, co oznacza, że geometria przecięta przez tę płaszczyznę pozostanie na swoim miejscu, podczas gdy reszta powierzchni zostanie pochylona pod zadanym kątem. Użycie do tego celu dolnej powierzchni wyciągnięcia nie jest dobrym pomysłem, ponieważ grubość ścianki w górnej części uchwytu stałaby się mniejsza niż 5 mm. Dlatego tworzymy płaszczyznę datum odsuniętą o około 35 mm od płaszczyzny XY. Aktywuj Zawartość ze szkieletem i utwórz tam płaszczyznę, ponieważ będziemy jej potrzebować także do zastosowania pochylenia do innych obiektów. 
<br clear=all>

[[Image:HolderTop2-8.jpg|Pierwsza Zawartość z zastosowanym pochyleniem i zaokrągleniami|thumb|right|400px]]
Obrazek po prawej stronie pokazuje ukończoną pierwszą Zawartość z zastosowanym pochyleniem i zaokrągleniami. Zauważ, że zewnętrzne (wklęsłe) krawędzie mają większy promień zaokrąglenia wynoszący 5 mm, ponownie w celu uzyskania bardziej jednolitej grubości ścianki (więcej niż 5 mm nie jest możliwe, ponieważ po obróbce wnętrza uchwytu grubość ścianki stałaby się mniejsza niż 5 mm). <br clear=all>

<span id="Adding_the_bodies_for_the_bolts"></span>
== Dodawanie zawartości dla śrub ==

[[Image:HolderTop2-13.jpg|Szkic dla Zawartości dla śrub|thumb|right|400px]]
Śruby wymagają dwóch cylindrycznych Zawartości po obu stronach głównej Zawartości. Najlepiej uwzględnić kąt pochylenia 2 stopni już w szkicu. Próbowałem obrócić cylinder, a potem zastosować pochylenie, ale po odbiciu lustrzanym działy się dziwne rzeczy i nie mogłem dodać zaokrągleń, ponieważ powierzchnia w jakiś sposób się zniekształciła.

Szkic jest wymiarowany tak, aby oś obrotu znajdowała się w odległości 12 mm od średnicy zewnętrznej Zawartości szkieletu: 7 mm na promień otworu plus 5 mm na grubość ścianki. Dla zachowania pełnej parametryczności elementu warto dodać do szkieletu płaszczyznę około 25 mm nad płaszczyzną XY, aby oznaczyć górę cylindrów. Ponieważ część ta będzie obrabiana, szkic jest wymiarowany 3 mm powyżej tej płaszczyzny.

<br clear=all>

[[Image:HolderTop2-14.jpg|Zawartośćdla śrub|thumb|right|400px]]
Utwórz wyciągnięcie przez obrót ze szkicu i zastosuj zaokrąglenie o wartości 4 mm na górze. Oznacza to, że po obróbce 3 mm pozostanie niewielki promień, co pomaga uniknąć ostrej krawędzi, przy której można by się skaleczyć podczas dokręcania śruby. 
<br clear=all>

[[Image:HolderTop2-16.jpg|Główna Zawartość z dwiema Zawartościami dla śrub|thumb|right|400px]]
Utwórz cechę operacji logicznej, aby połączyć główną Zawartość z Zawartością śrub. Następnie utwórz nową Zawartość dla drugiej strony. Skopiuj szkic wyciągnięcia przez obrót, przenieś go do tej Zawartości i utwórz drugą Zawartość dla śrub (odbicie lustrzane Zawartości nie jest jeszcze obsługiwane, więc większość trzeba zrobić od nowa). Następnie połącz tę drugą Zawartość również z główną Zawartością. Na koniec zastosuj duże zaokrąglenie na krawędzi utworzonej przez operację logiczną scalenia. Największe, jakie udało mi się uzyskać, to 4 mm. <br clear=all>

<span id="Hollowing_out_the_main_body"></span>
== Wydrążenie głównej Zawartości ==

[[Image:HolderTop2-9.jpg|Pierwsze wyciągnięcie Zawartości wyciętej wewnętrznej części w głównej Zawartości|thumb|right|300px]]
Teraz zajmiemy się wnętrzem uchwytu i wydrążymy je, aby zrobić miejsce na łożysko i pierścienie uszczelniające. Przy tym oczywiście musimy pamiętać o zapasie obróbkowym 3 mm. Ponieważ ten samouczek uczy metody wielobryłowej, utworzymy geometrię wewnętrzną jako oddzielną zawartość, a następnie wytniemy ją z głównej Zawartości za pomocą operacji logicznej.

Utwórz nową Zawartość i aktywuj ją. Najpierw potrzebujemy płaszczyzny konstrukcyjnej odsuniętej o 3 mm wewnątrz ściany szkieletu, która pokazuje stronę łożyska. Następnie skopiuj szkic pierwszego wyciągnięcia głównej Zawartości. Zostanie on dodany do głównej Zawartości, więc kliknij go prawym przyciskiem i wybierz opcję przeniesienia do nowo utworzonej Zawartości (ta opcja jest dostępna w menu kontekstowym tylko wtedy, gdy aktywne jest środowisko Projekt Części). Przypisz szkic do płaszczyzny konstrukcyjnej (jeśli szkic obróci się do góry nogami po przypisaniu, przenieś płaszczyznę konstrukcyjną na drugą stronę łożyska, obok miejsca, gdzie znajduje się skopiowany szkic). Teraz zmodyfikuj szkic tak, aby średnica była o 3 mm mniejsza od średnicy zewnętrznej geometrii szkieletu reprezentującej łożysko. Wystarczy usunąć wymiar 5 mm, przesunąć szkic do wnętrza koła odniesienia i utworzyć nowy wymiar 3 mm.
<br clear=all>

[[Image:HolderTop2-10.jpg|Wycięta zawartość wewnątrz Zawartości szkieletu|thumb|right|400px]]
Następnie utworzymy dwa kolejne wyciągnięcia, aby wydrążyć miejsce na pierścienie uszczelniające. Skopiuj szkic pierwszego wyciągnięcia wyciętej Zawartości i przypisz go do płaszczyzny XZ. Edytuj szkic, zastępując zewnętrzne odniesienie średnicą zewnętrzną pierścienia uszczelniającego łożyska. Wyciągnij ten szkic do odsunięcia 3 mm od strony pierścienia uszczelniającego. Cały proces powtórz dla pierścienia uszczelniającego po drugiej stronie.

Następnie utworzymy dwa kolejne wyciągnięcia podobne do ostatnich dwóch, aby zapewnić wałowi luz (np. 3 mm) wewnątrz uchwytu.
<br clear=all>

[[Image:HolderTop2-11.jpg|Kompletna wycięta Zawartość (oprócz niemożliwych zaokrągleń)|thumb|right|400px]]
Teraz pozostało tylko zastosować pochylenie do płaskich powierzchni bocznych, używając tej samej płaszczyzny neutralnej co dla głównej Zawartości, oraz wykonać zaokrąglenia. Zastosuj ogólne zaokrąglenie 3 mm do wszystkich krawędzi. Zauważysz, że istnieje kilka krawędzi, których nie da się zaokrąglić... jest to wada używanego przez FreeCAD jądra geometrycznego.
<br clear=all>

[[Image:HolderTop2-15.jpg|Ukończona surowa Zawartość uchwytu (bez obróbki)|thumb|right|400px]]
Jesteśmy gotowi do wydrążenia głównej Zawartości. Wybierz ją i utwórz nową operację logiczną. Dodaj wyciętą Zawartość do listy i ustaw operację na "Wytnij". Na dwóch krawędziach powstałych w wyniku wycięcia zastosuj zaokrąglenie 3 mm (niektóre krawędzie nadal pozostaną niemożliwe do zaokrąglenia). Wynik powinien wyglądać jak na obrazku po prawej.

Surowa część jest teraz ukończona. Tak będzie wyglądał uchwyt przed obróbką. Zauważ, że ponieważ forma będzie składała się z górnej i dolnej części, krawędzi między nimi nie da się zaokrąglić. Ponadto, jeśli przekażesz ten model odlewni, pamiętaj, aby zaznaczyć, że wymiary dotyczą stanu po odlewaniu. Odlewnia będzie musiała zastosować odpowiedni procent skurczu do modelu (powiększając cyfrowy model używany do wykonania formy, tak aby po ostygnięciu i skurczeniu metalu element miał właściwe wymiary).
<br clear=all>

<span id="Machining"></span>
==Obróbka skrawaniem==

[[Image:HolderTop2-17.jpg|Szkic do "wiercenia" otworów dla śrub|thumb|right|400px]]
Aby usunąć materiał potrzebny do obróbki wnętrza uchwytu, bardzo wygodnie można użyć samej Zawartości szkieletu. Jeśli nie chcesz tego robić, bo wtedy szkielet zostaje ukryty gdzieś głęboko w drzewku, możesz również skopiować szkic funkcji wyciągnięcia przez obrót szkieletu i odtworzyć wyciągnięcie przez obrót w innej Zawartości. Nie jest to jednak w pełni parametryczne, ponieważ skopiowany szkic jest niezależny od oryginału, więc przy zmianie wymiaru będziesz musiał edytować oba. W przyszłości możliwe jest wsparcie dla zależnych kopii funkcji.

For the rest of the machining, create a new Body. The bottom of the holder will be machined by a Pad sketched on the XY-plane extending downwards. Next, sketch a revolution to make a hole for the bolts. You will need to sketch on the XZ-plane and revolve it so that you can choose the outer diameter of the skeleton Body as an external reference. The top part of the sketch will serve to machine a flat place for the head of the bolt. It is dimensioned to leave at least 5mm wall thickness in the holder. If this does not give enough space for the bolt head then you can move the datum plane upwards. Of course, you could put this logic into the Skeleton, which is left as an exercise to the reader!
<br clear=all>

[[Image:HolderTop2-18.jpg|The machining Body|thumb|right|400px]]
You can mirror the revolution on the YZ-axis. The picture on the right shows the "machining" Body. Of course, most of the dimensions of the Pads and Revolutions are not important as long as there is plenty of overlap.
<br clear=all>

[[Image:HolderTop2-19.jpg|The finished Holder with machining|thumb|right|400px]]
Finally, create a boolean operation to cut the machining Body out of the main Body. If you want a nice visual effect, you can colour the machined surfaces differently from the rest of the part. This is also a useful optical feedback showing you whether you forgot to machine somewhere.
<br clear=all>

==Część pierwsza==
[[PartDesign_Bearingholder_Tutorial_I/pl|Poradnik: Projekt części, uchwyt łożyska cześć 1]]


[[Category:Tutorials{{#translation:}}]]
{{clear}}