<languages/>

{{TutorialInfo/fr
|Class=Modélisation
|Topic=Création d'une paire de roues dentées coniques
|Level=Avancé
|Time=À déterminer
|Author=[[User:FBXL5|FBXL5]]
|FCVersion=1.1
|SeeAlso=[[Gear_Workbench/fr|Atelier Gear]]
}}

<span id="Introduction"></span>
== Introduction ==

Le tutoriel '''Roues dentéesconiques''' décrit comment rassembler les données nécessaires pour créer une paire de roues dentées coniques à l'aide de l'outil [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/fr|Roue dentée conique]] de l'atelier [[Image:FCGear_workbench_icon.svg|16px]] [[Gear_Workbench/fr|Gear]] dans un contexte de [[Image:Workbench PartDesign.svg|16px]] [[PartDesign_Workbench/fr|PartDesign]].

[[Image:BevelGears_Example00.png|300px]]

{{Caption|Deux roues dentées coniques en prise}}

Une roue dentée conique peut être construite à partir du cercle primitif ou à partir du sommet (primitif), son extrémité virtuelle, en fonction de sa propriété « reset_origin ». Dans les étapes suivantes de ce tutoriel, nous devons mettre à l'échelle la roue conique tout en conservant son sommet en place. Nous allons donc décocher cette propriété. 

<span id="Requirements"></span>
== Conditions ==

L'outil [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/fr|Roue dentée conique]] crée un engrenage conique pour des axes perpendiculaires et un rapport de 1:1 par défaut. Pour d'autres angles entre leurs axes, mieux connus sous le nom d'angles d'arbre, et différents rapports, nous devons déterminer l'angle de cône approprié pour les deux roues dentées coniques appariées. De plus, nous devons ajuster les valeurs de base et dériver les diamètres primaires. 

<span id="Basic_Values"></span>
===Valeurs de base===

En supposant que nous nous sommes creusé la tête pour réfléchir à l'espace disponible, aux charges, au rapport et l'angle d'arbre, et avons maintenant trouvé ces valeurs de base :
: Module : <math>m = 2 mm</math>
: Rapport : <math>5 : 3</math>
: Angle d'arbre : <math>\Sigma = 60^\circ</math>

<span id="Number_of_Teeth"></span>
===Nombre de dents===

Afin de ne pas surcharger nos processeurs, nous allons définir le nombre de dents (z) du petit engrenage à seulement {{Value|9}} et donc le nombre de dents du grand engrenage à (<math>15 : 9</math> equals <math>5 : 3</math>).
: <math>z_1 = 15</math> (pour la '''roue dentée conique 1''')
: <math>z_2 = 9</math> (pour la '''roue dentée conique 2''')

<span id="Pitch_Diameter"></span>
===Diamètre primitif===

Nous pouvons maintenant calculer les diamètres primaires (d) :
: <math>d_1 = z_1 \cdot m = 15 \cdot 2 mm = 30 mm</math>
: <math>d_2 = z_2 \cdot m = 9 \cdot 2 mm = 18 mm</math>

<span id="Cone_Angles"></span>
=== Angles des cônes ===

C'est maintenant au tour de FreeCAD de trouver les angles du cône de pas (δ) :
# Créez un [[Image:Std_New.svg|16px]] [[Std_New/fr|nouveau document]].
# Créez un [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/fr|corps]] ('''Body''').
# Créer une [[Image:Sketcher_NewSketch.svg|16px]] [[PartDesign_NewSketch|esquisse]].

Nous utilisons l'esquisse pour dessiner deux triangles connectés dont les axes de symétrie sont perpendiculaires aux côtés représentant les diamètres primaires. Outre plusieurs contraintes cachées de coïncidence et de symétrie, nous utilisons deux contraintes de longueur pour les diamètres primaires et une contrainte d'angle pour l'angle d'arbre afin de contraindre entièrement l'esquisse. Nous pouvons ensuite utiliser deux contraintes de référence pour obtenir les deux angles du cône primitif (et quitter l'esquisse) :

[[Image:BevelGears_Example01.png|300px]]

{{Caption|En rouge : angle d'arbre contraint et deux diamètres primitifs<br>En bleu : angles des cônes primitifs résultants}}

Nous avons maintenant les angles des cônes primitifs :
: <math>\delta_1 = 38.21^\circ</math>
: <math>\delta_2 = 21.79^\circ</math>

<span id="Raw_Gears"></span>
==Roues dentées brutes==

Nous sommes prêts à créer notre paire de roues dentées coniques.

<span id="Bevel_Gear_1"></span>
===Roue dentée conique 1===

#Créez un nouveau [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/fr|PartDesign Corps]] ('''Body001''').
# Lancez la commande [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/fr|Roue dentée]].
# Une roue dentée conique ('''BevelGear''') est immédiatement créé, son côté diamètre primitif touchant l'origine, et attendant d'être ajusté.
# Dans l'[[Property_View/fr|éditeur de propriétés]], ajustez les propriétés suivantes de la roue dentée :
## Définissez la propriété {{PropertyData|module}} sur {{Value|2 mm}}.
## Définissez la propriété {{PropertyData|num_teeth}} sur {{Value|15}}.
## Définissez la propriété {{PropertyData|pitch_angle}} sur {{Value|38.21°}} (deux décimales devraient suffire).
## Décochez la propriété {{PropertyData|reset_origin}} pour placer le sommet de la roue dentée conique à l'origine (cela retournera la roue dentée).
# Utilisez [[Image:Std_TransformManip.svg|16px]] [[Std_TransformManip/fr|Transformer]] pour faire pivoter la roue dentée conique autour de l'origine de manière à ce que sa face côté cercle primitif soit parallèle à la ligne horizontale de l'esquisse représentant le même cercle primitif de la roue dentée la plus grande (si nous avons correctement renseigné les valeurs, la ligne devrait être coplanaire avec la face).

[[Image:BevelGears_Example02.png|300px]]

{{Caption|Roue dentée conique 1 correctement positionnée}}

<span id="Bevel_Gear_2"></span>
===Roue dentée conique 2===

# Créez un autre nouveau [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/fr|PartDesign Corps]] ('''Body002''').
# Lancez la commande [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/fr|Roue dentée conique]].
# Une roue dentée conique ('''BevelGear002''') est créé.
# Dans l'[[Property_View/fr|éditeur de propriétés]], ajustez les propriétés suivantes de la roue dentée conique :
## Définissez la propriété {{PropertyData|module}} sur {{Value|2 mm}}.
## Définissez la propriété {{PropertyData|num_teeth}} sur {{Value|9}}.
## Définissez la propriété {{PropertyData|pitch_angle}} sur {{Value|21.79°}}.
## Décochez la propriété {{PropertyData|reset_origin}} pour placer le sommet de la roue dentée conique à l'origine (cela retournera la roue dentée).
# Utilisez [[Image:Std_TransformManip.svg|16px]] [[Std_TransformManip/fr|Transformer]] pour faire pivoter la roue dentée conique autour de l'origine de manière à ce que sa face côté cercle primitif soit parallèle à la ligne oblique de l'esquisse représentant le même cercle primitif de la roue dentée la plus petite (si nous avons correctement renseigné les valeurs, la ligne devrait à nouveau être coplanaire avec la face).

[[Image:BevelGears_Example03.png|300px]]

{{Caption|Roue dentée conique 2 correctement positionnée}}

À ce stade, les deux roues dentées coniques devraient s'engrener l'un dans l'autre à l'endroit où leurs cônes de pas se rejoignent dans l'esquisse initiale, mais leurs formes ne ressemblent pas à celles des roues dentées coniques réelles.

[[Image:BevelGears_Example04.png|300px]]

{{Caption|Roues dentées brutes à denture conique en prise}}

Nous remarquons que l'outil [[Image:FCGear_BevelGear.svg|16px]] [[FCGear_BevelGear/fr|Roue dentée conique]] a prolongé le cône avant pour former le cône frontal avant de couper les dents, mais il n'a construit la roue dentée conique qu'à partir du cercle primitif vers le sommet (la pointe), et a ignoré la géométrie du cône arrière dans la direction opposée, comme le montre cette vue en coupe de la roue dentée conique finie :

[[Image:BevelGears_Example14.png|300px]]

{{Caption|En vert : cône avant<br>En rouge : cône central<br>En bleu : cône arrière}}

Pour obtenir une roue dentée conique correcte, nous devons agrandir nos roues dentées coniques brutes et découper la géométrie excédentaire, mais au lieu de découper, nous allons intersecter des objets de révolution définissant les sections transversales avec nos roues dentées coniques brutes à agrandir.

<span id="Intersection_Objects"></span>
==Objets d'intersection==

Nous devons définir les sections transversales souhaitées à partir de leurs axes vers l'extérieur, puis les faire pivoter pour créer des objets qui seront intersectés avec les résultats des étapes ci-dessus afin d'obtenir une paire appropriée de roues dentées coniques.

<span id="Revolution_Object_1"></span>
===Objet de révolution 1===

<div class="mw-translate-fuzzy">
# Activez le premier corps ('''Body''').
# Créez une autre [[Image:Sketcher_NewSketch.svg|16px]] [[PartDesign_NewSketch/fr|esquisse]], et dans l'esquisse :
## Projetez les lignes représentant les diamètres primitifs de notre première esquisse dans notre nouvelle esquisse.
## Tracez une ligne de construction à partir de leur point d'intersection jusqu'à l'origine (c'est ici que les cônes primitifs se rencontrent).
## Tracez une polyligne fermée de six lignes droites :
##* Une ligne colinéaire avec l'axe vertical de l'esquisse,
##* Deux lignes parallèles à la ligne de projection horizontale pour définir la position et l'épaisseur de la zone du moyeu,
##* Deux lignes perpendiculaires à la ligne de construction, dont une passant par le point d'intersection, qui définissent la largeur des dents,
##* Une ligne fermant la polyligne qui doit uniquement passer à l'extérieur de l'engrenage conique brut, car celui-ci a déjà une hauteur de dent correctement modélisée.
# Quittez l'esquisse.
# Créez un autre nouveau [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/fr|PartDesign corps]] ('''Body003''').
# Utilisez une [[Image:PartDesign_SubShapeBinder.svg|16px]] [[PartDesign_SubShapeBinder/fr|PartDesign Sous forme liée]] pour copier l'esquisse dans le corps.
# Créez un objet [[Image:PartDesign_Revolution.svg|16px]] [[PartDesign_Revolution/fr|de révolution]] ('''Revolution''') à partir de la sous forme liée.
</div>

[[Image:BevelGears_Example05.png|300px]] [[Image:BevelGears_Example06.png|300px]]

{{Caption|À gauche : esquisse de la section transversale.<br/>
À droite : objet de révolution résultant 1}}

La largeur des dents (également appelée largeur de face) correspond généralement à environ un tiers de la distance du cône (24,25° dans ce cas), c'est pourquoi 8 mm ont été choisis pour cet exemple.

<span id="Revolution_Object_2"></span>
===Objet de révolution 2===

<div class="mw-translate-fuzzy">
# Activez à nouveau le premier corps ('''Body''').
# Créez un autre [[Image:Sketcher_NewSketch.svg|16px]] [[PartDesign_NewSketch/fr|esquisse]], et dans l'esquisse :
## Projetez les lignes représentant les diamètres primitifs, ainsi que la ligne représentant l'axe de notre petit engrenage conique de notre première esquisse dans notre nouvelle esquisse.
## Tracez une ligne de construction à partir de leur point d'intersection des diamètres primitifs jusqu'à l'origine.
## Tracez une polyligne fermée de six lignes droites :
##* Une ligne colinéaire avec l'axe projeté,
##* Deux lignes parallèles au diamètre primitif projeté oblique pour définir la position et l'épaisseur de la zone du moyeu,
##* Deux lignes perpendiculaires à la ligne de construction, dont une passant par le point d'intersection, qui définissent la largeur des dents,
##* Une ligne fermant la polyligne qui doit uniquement passer à l'extérieur de l'engrenage conique brut, car celui-ci a déjà une hauteur de dent correctement modélisée.
# Quittez l'esquisse.
# Créez un autre nouveau [[Image:PartDesign_Body.svg|16px]] [[PartDesign_Body/fr|PartDesign corps]] ('''Body004''').
# Utilisez une [[Image:PartDesign_SubShapeBinder.svg|16px]] [[PartDesign_SubShapeBinder/fr|PartDesign Sous forme liée]] pour copier l'esquisse dans le corps.
# Créez un objet [[Image:PartDesign_Revolution.svg|16px]] [[PartDesign_Revolution/fr|de révolution]] ('''Revolution001''') à partir de la sous forme liée.
</div>

[[Image:BevelGears_Example07.png|300px]] [[Image:BevelGears_Example08.png|300px]]

{{Caption|À gauche : esquisse de la section transversale.<br/>
À droite : objet de révolution résultant 2}}

<span id="Finished_Bevel_Gears"></span>
==Roues dentées coniques finies==

Nous allons maintenant intersecter les roues dentées coniques brutes avec les objets de révolution afin de trouver leurs formes communes. Après avoir masqué tous les objets sauf nos roues dentées coniques brutes et nos objets de révolution, nous remarquons que les roues dentées ne dépassent pas suffisamment de l'objet de révolution. Comme nous avons construit les roues dentées coniques à partir des sommets, nous pouvons (mal) utiliser la valeur du module pour « mettre à l'échelle » l'engrenage et ajuster sa hauteur avant l'intersection.

<span id="Bevel_Gear_1"></span>
===Roue dentée conique 1===

# Activez la roue dentée conique 1 ('''Body001''').
# Dans l'[[Property_View/fr|éditeur de propriétés]], réglez les propriétés suivantes de la roue dentée conique :
## Définissez la propriété {{PropertyData|module}} sur {{Value|2.5 mm}}.
## Définissez la propriété {{PropertyData|height}} sur {{Value|15 mm}}.
# Appuyez sur le bouton {{Button|[[Image:Std_Refresh.svg|16px]] [[Std_Refresh/fr|Recalculer]]}} pour voir les modifications.
# Lancez [[Image:PartDesign_Boolean.svg|16px]] [[PartDesign_Boolean/fr|Créer une opération booléenne]].
# La boîte de dialogue '''Paramètres booléens''' s'ouvre dans le [[Task_Panel/fr|panneau des tâches]] :
#* Appuyez sur le bouton {{Button|Ajouter un corps}}.
#* Sélectionnez l'objet de révolution 1 ('''Body003''').
#* Appuyez à nouveau sur le bouton {{Button|Ajouter un corps}} pour terminer la sélection.
#* Sélectionnez '''Intersection''' parmi les options situées sous la liste.
# Appuyez sur le bouton {{Button|OK}} pour fermer la boîte de dialogue et terminer l'opération.
# La forme de la roue dentée conique 1 est terminée.

[[Image:BevelGears_Example09.png|300px]] [[Image:BevelGears_Example10.png|300px]]

{{Caption|À gauche : roue dentée conique 1 brute agrandie et objet de révolution 1.<br/>
À droite : roue dentée conique 1 terminée}}

<span id="Bevel_Gear_2"></span>
===Roue dentée conique 2===

# Activez la roue dentée conique 1 ('''Body001''').
# Dans l'[[Property_View/fr|éditeur de propriétés]], réglez les propriétés suivantes de la roue dentée conique :
## Définissez la propriété {{PropertyData|module}} sur {{Value|2.5 mm}}.
## Définissez la propriété {{PropertyData|height}} sur {{Value|15 mm}}.
# Appuyez sur le bouton {{Button|[[Image:Std_Refresh.svg|16px]] [[Std_Refresh/fr|Recalculer]]}} pour voir les modifications.
# Lancez [[Image:PartDesign_Boolean.svg|16px]] [[PartDesign_Boolean/fr|Créer une opération booléenne]].
# La boîte de dialogue '''Paramètres booléens''' s'ouvre dans le [[Task_Panel/fr|panneau des tâches]] :
#* Appuyez sur le bouton {{Button|Ajouter un corps}}.
#* Sélectionnez l'objet de révolution 2 ('''Body004''').
#* Appuyez à nouveau sur le bouton {{Button|Ajouter un corps}} pour terminer la sélection.
#* Sélectionnez '''Intersection''' parmi les options situées sous la liste.
# Appuyez sur le bouton {{Button|OK}} pour fermer la boîte de dialogue et terminer l'opération.
# La forme de la roue dentée conique 2 est terminée.

[[Image:BevelGears_Example11.png|300px]] [[Image:BevelGears_Example12.png|300px]]

{{Caption|À gauche : roue dentée conique 2 brute agrandie et objet de révolution 1.<br/>
À droite : roue dentée conique 2 terminée}}

<span id="Missing_Features"></span>
===Fonctions manquantes===

Pour accoupler deux roues dentées, nous utilisons généralement le cercle primitif, ou nous pouvons éventuellement utiliser le sommet en relation avec l'axe, mais le problème est que ni le cercle primitif ni le sommet ne sont représentés par un élément géométrique de la forme finale et ne peuvent donc pas être sélectionnés directement. Pour positionner les roues dentées dans un assemblage, nous devons ajouter/utiliser une géométrie auxiliaire sélectionnable qui peut être affichée/masquée à la demande, ou utiliser des éléments de forme existants dont le décalage par rapport au cercle primitif/au sommet est connu et saisir manuellement une valeur de décalage.

<span id="What_is_Left_to_do?"></span>
==Que reste-t-il à faire ?==

Nous avons maintenant deux engrenages coniques corrects, mais ils ne peuvent pas être montés sur des essieux ou des arbres. Ils doivent être prolongés par des éléments de forme, soit cylindriques pour que les roulements puissent tourner autour d'un essieu, soit prismatiques pour pouvoir transmettre le couple à un arbre. 

Ces ajouts sont assez simples à modéliser, ils ne sont donc pas abordés dans ce tutoriel.

Nous pourrions ajouter un objet de support et créer un assemblage animé, mais cela fera l'objet d'un autre tutoriel.

[[Image:BevelGears_Example13.gif|300px]]